### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lah90** [ikaruswill/whatsapp-media-tools#3]
Hi Will, would you be able to help me with this? I am not a coder so its super complicated for me, but would really appreciate if there was some way you could help me identifying the actual creation date of two pictures sent to me on Whatsapp. Best wishes, Lara

**Comment by ikaruswill** [comment]
Hey Lara, generally speaking, you can infer the creation date of those pictures by their filename.

For example: `IMG-20220312-WA0000.jpg` means that this picture was taken on Mar 12, 2022. But that's assuming that the photo was sent immediately after it was taken. The time that it was taken cannot be inferred from the filename.

You may get more accurate information from the photo itself within your phone. 
- Assuming you're using an Android phone, you can open a gallery/file explorer app and check on the photo's "details" screen. 
- I do not have an Apple phone so I'm unable to outline the instructions for iOS, but the overall steps remain the same. 
- Look for the 'exif' data, there should be a timestamp associated with the photo and that reflects the date and time the photo was supposedly taken. 
- There is a chance, however that this information may not be present, and if that's the case, I'm afraid the only way is the above method of inferring from the file name.

**Comment by ikaruswill** [comment]
Closing the issue for now as it's not an issue with the code, but I'd be happy to continue helping.

**Comment by lah90** [comment]
Thank you so much for your help, very kind. The image was sent to me on Whatsapp and I have read that Whatsapp deleted the Metadata? Is there anyway of finding out when the picture was taken (not sent) anyway? Thank you!!

**Comment by ikaruswill** [comment]
WhatsApp discards the metadata only if you've restored from backup once. 

Let's take for example you switched to a new phone in 3 Sep 2019, then all photos from before 3 Sep 2019, are restored from backup to your new phone. Those photos therefore will no longer have the date metadata (taken date).

 If let's say you didn't switch phones (and consequently restored your phone from backup), the date metadata should still be in the photo, you'll just have to inspect the file with a file manager app or gallery app of sorts, try to use whatever came with your phone first. Look for "Properties" or "Details".

**Comment by lah90** [comment]
Oh okay I understand. So lets say a picture was sent to me yesterday on Whatsapp - I should be able to see the the Metadata? Because I checked and it seems like there is no Metadata and the details are always the time it was sent?

Thank you again for your help!!
